services:
  gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - problems
      - submissions
      - plagiarism

  problems:
    build: ./problems-service-go
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/codejudgedb?sslmode=disable

  submissions:
    build: ./submissions-service-go
    depends_on:
      - db
      - redis
    # FIX: Mount the shared volume so it can write files for the judge
    volumes:
      - ./submissions_volume:/app/submissions
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/codejudgedb?sslmode=disable
      - REDIS_URL=redis
      

  plagiarism:
    build: ./plagiarism-service-go
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/codejudgedb?sslmode=disable
      - REDIS_URL=redis:6379

  judge:
    build: ./judge-service
    depends_on:
      - redis
      - db # Add dependency on the database
    # FIX: Mount the shared volume so it can read submission files
    volumes:
        - ./submissions_volume:/app/submissions
    environment:
      - REDIS_URL=redis:6379
      # FIX: Add database URL for the judge to connect
      - DATABASE_URL=postgres://user:password@db:5432/codejudgedb?sslmode=disable

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codejudgedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  # FIX: Define the shared volume
  submissions_volume:

