apiVersion: apps/v1
kind: Deployment
metadata:
  name: plagiarism
  namespace: codejudge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plagiarism-service
  template:
    metadata:
      labels:
        app: plagiarism-service
    spec:
      containers:
      - name: plagiarism-service
        image: plagiarism-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: codejudge-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: codejudge-config
              key: REDIS_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: plagiarism
  namespace: codejudge
spec:
  selector:
    app: plagiarism-service
  ports:
  - port: 8080
    targetPort: 8002
  type: ClusterIP
