name: CI / Build images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and push Docker images to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        env:
          IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/codejudge
          TAG: ${{ github.sha }}
        run: |
          set -euo pipefail
          services=(api-gateway problems-service-go submissions-service-go plagiarism-service-go judge-service)
          for svc in "${services[@]}"; do
            echo "Building $svc"
            docker build -t "$IMAGE_PREFIX-$svc:$TAG" -f "$svc/Dockerfile" "$svc"
            docker push "$IMAGE_PREFIX-$svc:$TAG"
          done

  # Deployment stage removed; this workflow only builds and pushes images.
