name: Deploy maintenance page

on:
  push:
    paths:
      - 'maintenance-page/**'
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node (for optional build step)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Copy maintenance files
        run: |
          rm -rf out || true
          mkdir -p out
          cp -r maintenance-page/* out/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          keep_files: false
